keywords:
  any:
    # Core stack/roles you want to see
    - '\b(software\s+engineer|software\s+developer|developer|swe|sde|backend|front[-\s]?end|full[-\s]?stack|platform\s+engineer)\b'
    - '\b(\.net|c#|asp\.net|web api|mvc|blazor|wpf)\b'
    - '\b(react|angular|typescript)\b'
    - '\b(aws|azure|kubernetes|k8s|docker|microservices)\b'
  must_not:
    # Broad job types you never want
    - '\b(intern|internship|new\s*grad|new\-graduate|apprentice|co\-op)\b'
    - '\b(contract|contractor|consultant|temp|temporary)\b'
    # Sales/AE/Architect/etc.
    - '\b(account\s+executive|account\s+mgr|sales|solutions?\s+architect|pre[\- ]?sales|solutions?\s+engineer)\b'

locations_prefer:
  - 'Remote'
  - 'United States'
  - 'Remote US'
  - 'Remote, US'
  - 'Dallas'
  - 'Austin'

filters:
  # 1) Title must include one of these (whitelist)
  titles_must_include:
    - '\b(software\s+engineer|software\s+developer|developer|swe|sde|backend|front[-\s]?end|full[-\s]?stack|platform\s+engineer)\b'
    - '\b(\.net|c#|asp\.net)\b'
  
  # 2) Title must NOT include these (seniorities & roles you don't want)
  titles_must_not:
    - '\b(senior|sr\.|staff|principal|lead|manager|mgr|director|head|vp|architect)\b'

  exp_max_years: 5
  exp_must_not_patterns:
   # 6+ years, 7-10 years, etc.
    - '\b([6-9]|1[0-9]|2[0-9])\s*\+?\s*(years?|yrs?)\b'
    - '\b([6-9]|1[0-9]|2[0-9])\s*-\s*[0-9]{1,2}\s*(years?|yrs?)\b'
    # IC levels that typically imply 6+ years
    - '\b(ic[5-9]|l[5-9])\b' 

  
  # ✅ Only allow roles that are Remote US or in US states/cities
  locations_allow_any:
    - 'remote'
    - 'remote us'
    - 'remote - united states'
    - 'remote - us'
    - 'remote (us)'
    - 'remote - usa'
    - 'united states'
    - 'u.s.'
    - 'usa'
    - 'remote - usa'
    - 'remote us'
    - 'us-remote'
    - 'remote, us'
    - 'u.s.'
    - 'usa'
    - 'dallas'
    - 'austin'
    - 'houston'
    - 'texas'
    - 'alabama'
    - 'alaska'
    - 'arizona'
    - 'arkansas'
    - 'california'
    - 'colorado'
    - 'connecticut'
    - 'delaware'
    - 'florida'
    - 'georgia'
    - 'hawaii'
    - 'idaho'
    - 'illinois'
    - 'indiana'
    - 'iowa'
    - 'kansas'
    - 'kentucky'
    - 'louisiana'
    - 'maine'
    - 'maryland'
    - 'massachusetts'
    - 'michigan'
    - 'minnesota'
    - 'mississippi'
    - 'missouri'
    - 'montana'
    - 'nebraska'
    - 'nevada'
    - 'new hampshire'
    - 'new jersey'
    - 'new mexico'
    - 'new york'
    - 'north carolina'
    - 'north dakota'
    - 'ohio'
    - 'oklahoma'
    - 'oregon'
    - 'pennsylvania'
    - 'rhode island'
    - 'south carolina'
    - 'south dakota'
    - 'tennessee'
    - 'utah'
    - 'vermont'
    - 'virginia'
    - 'washington'
    - 'washington d.c.'
    - 'west virginia'
    - 'wisconsin'
    - 'wyoming'

  locations_must_not:
    - 'canada'
    - 'mexico'
    - 'brazil'
    - 'italy'
    - 'france'
    - 'netherlands'
    - 'germany'
    - 'poland'
    - 'spain'
    - 'uk'
    - 'united kingdom'
    - 'ireland'
    - 'europe'
    - 'emea'
    - 'apac'
    - 'singapore'
    - 'india'
    - 'australia'
    - 'new zealand'
    - 'saudi arabia'
    - 'serbia'
    - 'denmark'
    - 'japan'
    - 'china'
    - 'hong kong'
    - 'south korea'

companies:
  greenhouse:
    - brex
    - paylocity
    - stripe
    - snowflake
    - cloudflare
    - okta
    - retool
    - doordash
    - databricks
    - coinbase
  lever:
    - datadog
    - block
    - robinhood
    - notion
    - rippling
    - airbnb
    - discord
    - plaid
    - twilio
    - dropbox
  ashby: []

watchlist_companies:
  - meta
  - microsoft
  - amazon
  - gm financial
  - goldman sachs
  - servicenow
  - pdi

email:
  from_name: 'Job Watcher'
  subject_prefix: '[NEW JOB]'
