keywords:
  any:
    - '\b(\.net|dot\s*net|dotnet|net\s*core|asp\.?net(?:\s*core)?|c\#|c\s*sharp|mvc|wpf|web\s*api)\b'
    - '\b(react|angular|typescript)\b'
    # - '\b(aws|azure|kubernetes|k8s|docker|microservices)\b'
    - '\b(software\s+engineer(?:\s*(?:i{1,3}|ii|iii|iv|v|[1-5]))?|software\s+developer|developer|swe|sde|backend|front[-\s]?end|full[-\s]?stack|platform\s+engineer|associate\s+developer|full[-\s]?stack\s+developer)\b'

  must_not:
    - '\b(intern|internship|new\s*grad|new\-graduate|apprentice|co\-op)\b'
    - '\b(contract|contractor|consultant|temp|temporary)\b'
    - '\b(account\s+executive|account\s+mgr|sales|solutions?\s+architect|pre[\- ]?sales|solutions?\s+engineer)\b'

locations_prefer:
  - 'Remote'
  - 'Remote US'
  - 'United States'
  - 'Remote, US'
  - 'Dallas'
  - 'Austin'

filters:
  titles_must_include:
    - '\b(software\s+engineer(?:\s*(?:i{1,3}|ii|iii|iv|v|[1-5]))?)\b'
    - '\b(software\s+developer)\b'
    - '\b(developer)\b'
    - '\b(sde(?:\s*[i1]{0,2})?)\b'
    # - '\b(swe)\b'
    - '\b(backend)\b'
    - '\b(front[-\s]?end)\b'
    - '\b(full[-\s]?stack)\b'
    - '\b(platform\s+engineer)\b'
    - '\b(associate\s+developer)\b'
    - '\b(full[-\s]?stack\s+developer)\b'
    - '\b(engineer)\b'

  titles_must_not:
    - '\b(senior|sr\.|staff|principal|lead|manager|mgr|director|head|vp|architect)\b'

  exp_max_years: 5
  exp_must_not_patterns:
    - '\b([6-9]|1[0-9]|2[0-9])\s*\+?\s*(years?|yrs?)\b'
    - '\b([6-9]|1[0-9]|2[0-9])\s*-\s*[0-9]{1,2}\s*(years?|yrs?)\b'
    - '\b(ic[5-9]|l[5-9])\b'

  locations_allow_any:
    - 'remote'
    - 'remote us'
    - 'remote - united states'
    - 'remote - us'
    - 'remote (us)'
    - 'remote - usa'
    - 'united states'
    - 'us'
    - 'remote, us'
    - 'dallas'
    - 'austin'
    - 'houston'
    - 'tx'
    - 'ca'
    - 'wa'
    - 'ny'
    - 'nj'
    - 'ma'
    - 'il'
    - 'co'
    - 'fl'
    - 'ga'
    - 'nc'
    - 'va'
    - 'pa'
    - 'or'
    - 'az'
    - 'oh'
    - 'mi'
    - 'ut'
    - 'mn'
    - 'wi'
    - 'tn'
    - 'md'
    - 'dc'

  locations_must_not:
    - 'canada'
    - 'mexico'
    - 'brazil'
    - 'italy'
    - 'france'
    - 'netherlands'
    - 'germany'
    - 'poland'
    - 'spain'
    - 'uk'
    - 'united kingdom'
    - 'ireland'
    - 'europe'
    - 'emea'
    - 'apac'
    - 'singapore'
    - 'india'
    - 'australia'
    - 'new zealand'
    - 'saudi arabia'
    - 'serbia'
    - 'denmark'
    - 'japan'
    - 'china'
    - 'hong kong'
    - 'south korea'

companies:
  greenhouse:
    - brex
    - paylocity
    - stripe
    - snowflake
    - cloudflare
    - okta
    - retool
    - doordash
    - databricks
    - coinbase
    - plaid
    - twilio
    - notion
    - airbnb
    - discord
    - robinhood
    # more GH slugs:
    - atlassian
    - asana
    - gitlab
    - hashicorp
    - figma
    - instacart
    - zapier
    - scaleai
    - peloton

  lever:
    - datadog
    - block
    - dropbox
    - rippling
    - slack
    - coursera
    - reddit
    - affirm
    # more Lever handles:
    - klarna
    - box
    - niantic
    - docusign
    - robinhood
    - ro
    - duolingo

  ashby:
    - openai
    - figma
    - notion
    - scaleai
    - flexport
    # more Ashby orgs:
    - ramp
    - linear
    - mercury
    - vercel
    - retool
    - sora
    - humane

  smartrecruiters:
    - cisco
    - square
    - samsung
    # more SR companies:
    - nokia
    - pepsico
    - bosch
    - hewlett-packard
    - pinterest

  recruitee:
    - algolia
    - trivago
    - bynder
    - sendcloud
    - bunq
    - messagebird
    - mobiquity

  # NEW: Amazon public JSON search
  amazon:
    base: "https://www.amazon.jobs/en/search.json"
    # You can tweak these filters. Common options include:
    #   category: "Software Development"
    #   normalized_country_code: "USA"
    #   query: ".NET"  (or "C#", "Software Engineer", etc.)
    #   business_category, job_function (varies)
    query_params:
      category: "Software Development"
      normalized_country_code: "USA"
      result_limit: 100
      sort: "recent"
      query: ".NET OR C# OR \"Software Engineer\" OR \"Full Stack\""

  # NEW: Workday CxS monitors (Microsoft, Meta, and any other Workday tenant that exposes CxS)
  # NOTE: The exact host/tenant/org vary by company. These examples are illustrative; adjust if needed.
  # --- add/merge under root-level `companies:` ---
companies:
  # 1) Greenhouse (list their slugs)
  greenhouse:
    - brex
    - paylocity
    - stripe
    - snowflake
    - cloudflare
    - okta
    - retool
    - doordash
    - databricks
    - coinbase
    - plaid
    - twilio
    - notion
    - airbnb
    - discord
    - robinhood

  # 2) Lever (company handles)
  lever:
    - datadog
    - block
    - dropbox
    - rippling
    - slack
    - coursera
    - reddit
    - affirm

  # 3) Ashby (org slugs)
  ashby:
    - openai
    - figma
    - scaleai
    - flexport
    # - notion   # (notion is Greenhouse; keep it above)

  # 4) SmartRecruiters (company slugs)
  smartrecruiters:
    - cisco
    - square

  # 5) Recruitee (company slugs)
  recruitee:
    - bolt
    - sendcloud

  # 6) Amazon (site-wide JSON; tune `query_params`)
  amazon:
    base: "https://www.amazon.jobs/en/search.json"
    query_params:
      query: ".NET OR C# OR backend"
      normalized_country_code: "USA"
      result_limit: 100
      sort: "recent"

  # 7) Workday CxS (generic adapter; add each site with host/tenant/org)
  workday_cxs:
    - name: "Stripe"
      host: "stripe.wd1.myworkdayjobs.com"
      tenant: "stripe"
      org: "Stripe_Careers"
      search:
        searchText: ".NET backend"   # free text
        page: 1
    - name: "Snowflake"
      host: "snowflakeinc.wd5.myworkdayjobs.com"
      tenant: "snowflakeinc"
      org: "Snowflake"
      search:
        searchText: "Software Engineer"
    - name: "Databricks"
      host: "databricks.wd1.myworkdayjobs.com"
      tenant: "databricks"
      org: "External"
      search:
        searchText: ".NET OR C#"
    - name: "Okta"
      host: "okta.wd1.myworkdayjobs.com"
      tenant: "okta"
      org: "Okta_External_Careers"
      search:
        searchText: "backend"

  # 8) Google Careers (site API; tweak params)
  google:
    bases:
      - "https://careers.google.com/api/v3/search/"
      - "https://careers.google.com/api/v2/search/"
    query_params:
      q: ".NET OR C# OR backend"
      page_size: 100
      location: "United States"

  # NEW: Google Careers (read-only)
  google:
    # We'll try these bases in order; you can add/remove as needed.
    bases:
      - "https://careers.google.com/api/v3/search/"
      - "https://careers.google.com/api/v2/search/"
      - "https://careers.google.com/api/v1/search/"
    # Tweak the query to your taste.
    # Common keys that have worked historically: q, page, page_size, skills, location, degree, employment_type
    query_params:
      q: ".NET OR C# OR \"ASP.NET\" OR \"Full Stack\" OR \"Software Engineer\""
      page_size: 100
      # If you want only US roles, try one (or both) of these depending on what the current API supports:
      # location: "United States"
      # skills: ".NET,C#"

watchlist_companies:
  - meta
  - microsoft
  - amazon
  - gm financial
  - goldman sachs
  - servicenow
  - pdi

email:
  from_name: 'Job Watcher'
  subject_prefix: '[NEW JOB]'
