# -----------------------------
#  Job Watcher config (C#/.NET)
# -----------------------------

keywords:
  any:
    # Broad relevance gate (extra safety alongside tech_filters)
    - '\b(software\s+engineer|software\s+developer|developer|swe|sde|backend|front[-\s]?end|full[-\s]?stack|platform\s+engineer)\b'
    - '\b(\.net|c#|csharp|asp\.net|web\s*api|mvc|blazor|wpf)\b'
    - '\b(react|angular|typescript)\b'
    - '\b(aws|azure|kubernetes|k8s|docker|microservices)\b'
  must_not:
    # Roles you never want
    - '\b(intern|internship|new\s*grad|new\-graduate|apprentice|co\-op)\b'
    - '\b(contract|contractor|consultant|temp|temporary)\b'
    - '\b(account\s+executive|account\s+mgr|sales|solutions?\s+architect|pre[\- ]?sales|solutions?\s+engineer)\b'

locations_prefer:
  - 'Remote'
  - 'Remote US'
  - 'United States'
  - 'Dallas'
  - 'Austin'
  - 'Houston'
  - 'Texas'

filters:
  # 1) Title must include one of these (role gate)
  titles_must_include:
    - '\b(software\s+engineer|software\s+developer|developer|swe|sde|backend|front[-\s]?end|full[-\s]?stack|platform\s+engineer)\b'
    - '\b(\.net|c#|csharp|asp\.net)\b'

  # 2) Title must NOT include (block obvious senior/management + very senior titles)
  titles_must_not:
    - '\b(senior|sr\.|staff|principal|lead|manager|mgr|director|head|vp|architect|distinguished|fellow)\b'

  # 3) Experience ceiling (<= 5 years)
  exp_max_years: 5
  exp_must_not_patterns:
    - '\b([6-9]|1[0-9]|2[0-9])\s*\+?\s*(years?|yrs?)\b'
    - '\b([6-9]|1[0-9]|2[0-9])\s*-\s*[0-9]{1,2}\s*(years?|yrs?)\b'
    - '\b(ic[5-9]|l[5-9])\b'

  # 4) US-only (allow Remote-US + US states/cities); block common non-US regions
  #    We also match state abbreviations via state_abbrev_regex below.
  locations_allow_any:
    - 'remote'
    - 'remote us'
    - 'remote - us'
    - 'remote - usa'
    - 'remote (us)'
    - 'remote, us'
    - 'remote - united states'
    - 'united states'
    - 'u.s.'
    - 'usa'
    - 'dallas'
    - 'austin'
    - 'houston'
    - 'texas'
    - 'alabama'
    - 'alaska'
    - 'arizona'
    - 'arkansas'
    - 'california'
    - 'colorado'
    - 'connecticut'
    - 'delaware'
    - 'florida'
    - 'georgia'
    - 'hawaii'
    - 'idaho'
    - 'illinois'
    - 'indiana'
    - 'iowa'
    - 'kansas'
    - 'kentucky'
    - 'louisiana'
    - 'maine'
    - 'maryland'
    - 'massachusetts'
    - 'michigan'
    - 'minnesota'
    - 'mississippi'
    - 'missouri'
    - 'montana'
    - 'nebraska'
    - 'nevada'
    - 'new hampshire'
    - 'new jersey'
    - 'new mexico'
    - 'new york'
    - 'north carolina'
    - 'north dakota'
    - 'ohio'
    - 'oklahoma'
    - 'oregon'
    - 'pennsylvania'
    - 'rhode island'
    - 'south carolina'
    - 'south dakota'
    - 'tennessee'
    - 'texas'
    - 'utah'
    - 'vermont'
    - 'virginia'
    - 'washington'
    - 'washington d.c.'
    - 'west virginia'
    - 'wisconsin'
    - 'wyoming'

  locations_must_not:
    - 'canada'
    - 'mexico'
    - 'brazil'
    - 'italy'
    - 'france'
    - 'netherlands'
    - 'germany'
    - 'poland'
    - 'spain'
    - 'uk'
    - 'united kingdom'
    - 'ireland'
    - 'europe'
    - 'emea'
    - 'apac'
    - 'singapore'
    - 'india'
    - 'australia'
    - 'new zealand'
    - 'saudi arabia'
    - 'serbia'
    - 'denmark'
    - 'japan'
    - 'china'
    - 'hong kong'
    - 'south korea'

  # Count "City, ST" as US (e.g., "Austin, TX", "Seattle, WA")
  state_abbrev_regex: ',\s*(AL|AK|AZ|AR|CA|CO|CT|DC|DE|FL|GA|HI|IA|ID|IL|IN|KS|KY|LA|MA|MD|ME|MI|MN|MO|MS|MT|NC|ND|NE|NH|NJ|NM|NV|NY|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VA|VT|WA|WI|WV)\b'

# Strict tech-stack gate for .NET/C#
tech_filters:
  must_all:
    - '\b(c#|csharp|\.net|asp\.net|web\s*api|mvc)\b'
  must_any:
    - '\b(azure|aws|kubernetes|k8s|docker|microservices)\b'
    - '\b(sql\s*server|mssql|ef\s*core|entity\s*framework)\b'
    - '\b(react|angular|typescript)\b'

companies:
  greenhouse:
    # existing
    - brex
    - paylocity
    - stripe
    - snowflake
    - cloudflare
    - okta
    - retool
    - doordash
    - databricks
    - coinbase
    # added (Greenhouse-hosted)
    - atlassian
    - asana
    - affirm
    - reddit
    - zapier
    - segment
    - loom
    - instacart
    - airbnb   # often on Lever too; harmless if dup
    - discord  # often on Lever; harmless if dup

  lever:
    # existing
    - datadog
    - block
    - robinhood
    - notion
    - rippling
    - airbnb
    - discord
    - plaid
    - twilio
    - dropbox
    # added (Lever-hosted)
    - figma
    - pinterestlabs
    - scaleai
    - box
    - splunk

  ashby:
    # add org slugs you care about (Ashby exposes a public non-user GraphQL)
    - vercel
    - linear
    - ramp
    - mercury
    - dbt-labs
    - census
    - hex-technologies
    - persona

watchlist_companies:
  - meta
  - microsoft
  - amazon
  - gm financial
  - goldman sachs
  - servicenow
  - pdi

email:
  from_name: 'Job Watcher'
  subject_prefix: '[NEW JOB]'
